apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-amf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
    spec:
      containers:
      - name: amf
        image: open5gs-core:latest
        imagePullPolicy: Never
        command: ["open5gs-amfd"]
